# docker build -f Dockerfile-Pecl -t ghcr.io/wingsun97/php-dev:8.3-cli-pecl .
# ============================
# 常用扩展（不涉及 grpc）
# ============================
FROM ghcr.io/wingsun97/php-dev:8.3-cli-grpc

RUN pecl install redis \
 && pecl install igbinary \
 # && pecl install imagick \
 && pecl install seaslog \
 && docker-php-ext-enable redis igbinary seaslog \
 && rm -rf /tmp/pear

WORKDIR /workspace
