# =========================
# Stage 1: build grpc（编译层）
# =========================
FROM ghcr.io/wingsun97/php-dev:8.3-cli-core AS builder

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
    git curl unzip \
    pkg-config autoconf g++ make re2c \
    cmake \
    libssl-dev zlib1g-dev \
    libprotobuf-dev protobuf-compiler \
 && rm -rf /var/lib/apt/lists/*

# 安装 grpc（锁版本）
RUN pecl channel-update pecl.php.net \
 && printf "\n" | pecl install grpc-1.76.0 \
 && docker-php-ext-enable grpc \
 && php -m | grep grpc

# =========================
# Stage 2: runtime（最终镜像）
# =========================
FROM ghcr.io/wingsun97/php-dev:8.3-cli-core

# 只安装运行时依赖（更小）
RUN apt-get update && apt-get install -y --no-install-recommends \
    libprotobuf-dev \
 && rm -rf /var/lib/apt/lists/*

# 拷贝编译好的扩展
COPY --from=builder /usr/local/lib/php/extensions/ /usr/local/lib/php/extensions/
COPY --from=builder /usr/local/etc/php/conf.d/ /usr/local/etc/php/conf.d/

# 验证（可选）
# RUN php -m | grep grpc